// Code generated by protoc-gen-go.
// source: circle.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 创建房间
type CCreateRoom struct {
	Code *uint32 `protobuf:"varint,1,opt,name=code,def=3003" json:"code,omitempty"`
	// required uint32 expire = 2;  //牌局设定的过期时间(牌局存在的时间单位/秒)
	Round            *uint32 `protobuf:"varint,2,req,name=round" json:"round,omitempty"`
	Rtype            *uint32 `protobuf:"varint,3,req,name=rtype" json:"rtype,omitempty"`
	Audience         *uint32 `protobuf:"varint,4,req,name=audience" json:"audience,omitempty"`
	Pub              *uint32 `protobuf:"varint,5,req,name=pub" json:"pub,omitempty"`
	Updownji         *uint32 `protobuf:"varint,6,req,name=updownji" json:"updownji,omitempty"`
	Horse            *uint32 `protobuf:"varint,7,req,name=horse" json:"horse,omitempty"`
	Cid              *uint32 `protobuf:"varint,8,req,name=cid" json:"cid,omitempty"`
	Rname            *string `protobuf:"bytes,9,req,name=rname" json:"rname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCreateRoom) Reset()                    { *m = CCreateRoom{} }
func (m *CCreateRoom) String() string            { return proto.CompactTextString(m) }
func (*CCreateRoom) ProtoMessage()               {}
func (*CCreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

const Default_CCreateRoom_Code uint32 = 3003

func (m *CCreateRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CCreateRoom_Code
}

func (m *CCreateRoom) GetRound() uint32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *CCreateRoom) GetRtype() uint32 {
	if m != nil && m.Rtype != nil {
		return *m.Rtype
	}
	return 0
}

func (m *CCreateRoom) GetAudience() uint32 {
	if m != nil && m.Audience != nil {
		return *m.Audience
	}
	return 0
}

func (m *CCreateRoom) GetPub() uint32 {
	if m != nil && m.Pub != nil {
		return *m.Pub
	}
	return 0
}

func (m *CCreateRoom) GetUpdownji() uint32 {
	if m != nil && m.Updownji != nil {
		return *m.Updownji
	}
	return 0
}

func (m *CCreateRoom) GetHorse() uint32 {
	if m != nil && m.Horse != nil {
		return *m.Horse
	}
	return 0
}

func (m *CCreateRoom) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *CCreateRoom) GetRname() string {
	if m != nil && m.Rname != nil {
		return *m.Rname
	}
	return ""
}

// 返回房间数据,
type SCreateRoom struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=3003" json:"code,omitempty"`
	Rdata            *RoomData `protobuf:"bytes,2,req,name=rdata" json:"rdata,omitempty"`
	Error            *uint32   `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCreateRoom) Reset()                    { *m = SCreateRoom{} }
func (m *SCreateRoom) String() string            { return proto.CompactTextString(m) }
func (*SCreateRoom) ProtoMessage()               {}
func (*SCreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

const Default_SCreateRoom_Code uint32 = 3003
const Default_SCreateRoom_Error uint32 = 0

func (m *SCreateRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SCreateRoom_Code
}

func (m *SCreateRoom) GetRdata() *RoomData {
	if m != nil {
		return m.Rdata
	}
	return nil
}

func (m *SCreateRoom) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SCreateRoom_Error
}

// 同圈子的玩家创建房间返回房间数据,广播给圈子在线玩家
type SOtherCreateRoom struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=3005" json:"code,omitempty"`
	Rdata            *RoomData `protobuf:"bytes,2,req,name=rdata" json:"rdata,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SOtherCreateRoom) Reset()                    { *m = SOtherCreateRoom{} }
func (m *SOtherCreateRoom) String() string            { return proto.CompactTextString(m) }
func (*SOtherCreateRoom) ProtoMessage()               {}
func (*SOtherCreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

const Default_SOtherCreateRoom_Code uint32 = 3005

func (m *SOtherCreateRoom) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SOtherCreateRoom_Code
}

func (m *SOtherCreateRoom) GetRdata() *RoomData {
	if m != nil {
		return m.Rdata
	}
	return nil
}

// 获取房间人数
type CUpdateRoomPerson struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3026" json:"code,omitempty"`
	Invitecode       *string `protobuf:"bytes,2,req,name=invitecode" json:"invitecode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CUpdateRoomPerson) Reset()                    { *m = CUpdateRoomPerson{} }
func (m *CUpdateRoomPerson) String() string            { return proto.CompactTextString(m) }
func (*CUpdateRoomPerson) ProtoMessage()               {}
func (*CUpdateRoomPerson) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

const Default_CUpdateRoomPerson_Code uint32 = 3026

func (m *CUpdateRoomPerson) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CUpdateRoomPerson_Code
}

func (m *CUpdateRoomPerson) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

type SUpdateRoomPerson struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3026" json:"code,omitempty"`
	Invitecode       *string `protobuf:"bytes,2,req,name=invitecode" json:"invitecode,omitempty"`
	Rid              *uint32 `protobuf:"varint,3,req,name=rid" json:"rid,omitempty"`
	Count            *uint32 `protobuf:"varint,4,req,name=count" json:"count,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SUpdateRoomPerson) Reset()                    { *m = SUpdateRoomPerson{} }
func (m *SUpdateRoomPerson) String() string            { return proto.CompactTextString(m) }
func (*SUpdateRoomPerson) ProtoMessage()               {}
func (*SUpdateRoomPerson) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

const Default_SUpdateRoomPerson_Code uint32 = 3026
const Default_SUpdateRoomPerson_Error uint32 = 0

func (m *SUpdateRoomPerson) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SUpdateRoomPerson_Code
}

func (m *SUpdateRoomPerson) GetInvitecode() string {
	if m != nil && m.Invitecode != nil {
		return *m.Invitecode
	}
	return ""
}

func (m *SUpdateRoomPerson) GetRid() uint32 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *SUpdateRoomPerson) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *SUpdateRoomPerson) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SUpdateRoomPerson_Error
}

// 指定圈子自己参与的前50个房间的牌局记录
type CPrivateCircleRecord struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3035" json:"code,omitempty"`
	Cid              *uint32 `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPrivateCircleRecord) Reset()                    { *m = CPrivateCircleRecord{} }
func (m *CPrivateCircleRecord) String() string            { return proto.CompactTextString(m) }
func (*CPrivateCircleRecord) ProtoMessage()               {}
func (*CPrivateCircleRecord) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

const Default_CPrivateCircleRecord_Code uint32 = 3035

func (m *CPrivateCircleRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPrivateCircleRecord_Code
}

func (m *CPrivateCircleRecord) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

type SPrivateCircleRecord struct {
	Code             *uint32                   `protobuf:"varint,1,opt,name=code,def=3035" json:"code,omitempty"`
	Cid              *uint32                   `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	Coin             *int32                    `protobuf:"varint,3,req,name=coin" json:"coin,omitempty"`
	Data             []*PrivateRecordForCircle `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	Error            *uint32                   `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *SPrivateCircleRecord) Reset()                    { *m = SPrivateCircleRecord{} }
func (m *SPrivateCircleRecord) String() string            { return proto.CompactTextString(m) }
func (*SPrivateCircleRecord) ProtoMessage()               {}
func (*SPrivateCircleRecord) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

const Default_SPrivateCircleRecord_Code uint32 = 3035
const Default_SPrivateCircleRecord_Error uint32 = 0

func (m *SPrivateCircleRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPrivateCircleRecord_Code
}

func (m *SPrivateCircleRecord) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *SPrivateCircleRecord) GetCoin() int32 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *SPrivateCircleRecord) GetData() []*PrivateRecordForCircle {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SPrivateCircleRecord) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPrivateCircleRecord_Error
}

//  指定房间牌局记录
type CPrivateRoomRecord struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=3036" json:"code,omitempty"`
	Cid              *uint32 `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	Rid              *uint32 `protobuf:"varint,3,req,name=rid" json:"rid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPrivateRoomRecord) Reset()                    { *m = CPrivateRoomRecord{} }
func (m *CPrivateRoomRecord) String() string            { return proto.CompactTextString(m) }
func (*CPrivateRoomRecord) ProtoMessage()               {}
func (*CPrivateRoomRecord) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

const Default_CPrivateRoomRecord_Code uint32 = 3036

func (m *CPrivateRoomRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPrivateRoomRecord_Code
}

func (m *CPrivateRoomRecord) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *CPrivateRoomRecord) GetRid() uint32 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

type SPrivateRoomRecord struct {
	Code             *uint32                 `protobuf:"varint,1,opt,name=code,def=3036" json:"code,omitempty"`
	Cid              *uint32                 `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	Rid              *uint32                 `protobuf:"varint,3,req,name=rid" json:"rid,omitempty"`
	Data             []*PrivateRecordForRoom `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	Error            *uint32                 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *SPrivateRoomRecord) Reset()                    { *m = SPrivateRoomRecord{} }
func (m *SPrivateRoomRecord) String() string            { return proto.CompactTextString(m) }
func (*SPrivateRoomRecord) ProtoMessage()               {}
func (*SPrivateRoomRecord) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

const Default_SPrivateRoomRecord_Code uint32 = 3036
const Default_SPrivateRoomRecord_Error uint32 = 0

func (m *SPrivateRoomRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPrivateRoomRecord_Code
}

func (m *SPrivateRoomRecord) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *SPrivateRoomRecord) GetRid() uint32 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *SPrivateRoomRecord) GetData() []*PrivateRecordForRoom {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SPrivateRoomRecord) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPrivateRoomRecord_Error
}

func init() {
	proto.RegisterType((*CCreateRoom)(nil), "protocol.CCreateRoom")
	proto.RegisterType((*SCreateRoom)(nil), "protocol.SCreateRoom")
	proto.RegisterType((*SOtherCreateRoom)(nil), "protocol.SOtherCreateRoom")
	proto.RegisterType((*CUpdateRoomPerson)(nil), "protocol.CUpdateRoomPerson")
	proto.RegisterType((*SUpdateRoomPerson)(nil), "protocol.SUpdateRoomPerson")
	proto.RegisterType((*CPrivateCircleRecord)(nil), "protocol.CPrivateCircleRecord")
	proto.RegisterType((*SPrivateCircleRecord)(nil), "protocol.SPrivateCircleRecord")
	proto.RegisterType((*CPrivateRoomRecord)(nil), "protocol.CPrivateRoomRecord")
	proto.RegisterType((*SPrivateRoomRecord)(nil), "protocol.SPrivateRoomRecord")
}

var fileDescriptor1 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x6b, 0xdb, 0x30,
	0x1c, 0xc5, 0xf1, 0xaf, 0xcd, 0xf9, 0x3a, 0x86, 0x44, 0xe4, 0x20, 0x76, 0x18, 0x9e, 0x4f, 0x3e,
	0x0c, 0x13, 0x12, 0x92, 0xc1, 0x76, 0x9b, 0xc7, 0x60, 0xa7, 0x85, 0x98, 0xed, 0xae, 0x49, 0x82,
	0x68, 0x24, 0x92, 0x51, 0xe4, 0x94, 0x5e, 0x7b, 0xe9, 0x1f, 0xd1, 0x7f, 0xb6, 0x58, 0xb1, 0xd3,
	0x86, 0x34, 0x6d, 0x49, 0x4f, 0xc6, 0x92, 0xde, 0xd3, 0xfb, 0xbc, 0xaf, 0xa0, 0x4f, 0x85, 0xa6,
	0x6b, 0x9e, 0x57, 0x5a, 0x19, 0x85, 0x42, 0xfb, 0xa1, 0x6a, 0xfd, 0x21, 0xdc, 0xa9, 0xfd, 0x5a,
	0x7a, 0xe7, 0x40, 0x54, 0x14, 0x9a, 0x13, 0xc3, 0x97, 0x4a, 0x6d, 0x10, 0x02, 0x9f, 0x2a, 0xc6,
	0xb1, 0x93, 0x38, 0x59, 0xfc, 0xd5, 0x9f, 0x8e, 0xc7, 0x53, 0x14, 0x43, 0xa0, 0x55, 0x2d, 0x19,
	0x76, 0x13, 0x37, 0x8b, 0xed, 0xaf, 0xb9, 0xae, 0x38, 0xf6, 0xec, 0xef, 0x00, 0x42, 0x52, 0x33,
	0xc1, 0x25, 0xe5, 0xd8, 0xb7, 0x2b, 0x11, 0x78, 0x55, 0xfd, 0x0f, 0x07, 0xdd, 0x76, 0x5d, 0x31,
	0x75, 0x25, 0xff, 0x0b, 0xfc, 0xae, 0xd3, 0xaf, 0x94, 0xde, 0x72, 0xfc, 0xbe, 0x3b, 0x4d, 0x05,
	0xc3, 0xe1, 0xc1, 0x5b, 0x92, 0x0d, 0xc7, 0xbd, 0xc4, 0xcd, 0x7a, 0xe9, 0x5f, 0x88, 0xca, 0x17,
	0xc2, 0x7d, 0x82, 0x40, 0x33, 0x62, 0x88, 0x0d, 0x17, 0x4d, 0x50, 0xde, 0x41, 0xe6, 0x8d, 0xe4,
	0x07, 0x31, 0x04, 0x0d, 0x20, 0xe0, 0x5a, 0x2b, 0x8d, 0x3d, 0xab, 0x73, 0xc6, 0xe9, 0x2f, 0x18,
	0x94, 0xbf, 0xcd, 0x8a, 0xeb, 0x67, 0xcd, 0x67, 0xaf, 0x30, 0x4f, 0xbf, 0xc1, 0xb0, 0xf8, 0x53,
	0xb1, 0xd6, 0x65, 0xc1, 0xf5, 0x56, 0xc9, 0x53, 0xaf, 0xc9, 0x1c, 0x21, 0x00, 0x21, 0x77, 0xc2,
	0x70, 0xbb, 0xe3, 0x5a, 0x3e, 0x01, 0xc3, 0xf2, 0x52, 0x71, 0x53, 0x9c, 0x16, 0xac, 0x9d, 0x42,
	0x0c, 0x01, 0x55, 0xb5, 0x34, 0xed, 0x08, 0x0e, 0xc8, 0x41, 0x87, 0xfc, 0x05, 0x46, 0xc5, 0x42,
	0x8b, 0x1d, 0x31, 0xbc, 0xb0, 0x8f, 0x62, 0xc9, 0xa9, 0xd2, 0xec, 0xf4, 0xb6, 0xe9, 0xac, 0x1b,
	0x89, 0x1d, 0x77, 0x7a, 0xeb, 0xc0, 0xa8, 0xbc, 0x44, 0x89, 0xfa, 0xcd, 0x01, 0x21, 0x6d, 0xc2,
	0x00, 0xe5, 0xe0, 0xdb, 0x2a, 0xfd, 0xc4, 0xcb, 0xa2, 0x49, 0xf2, 0x50, 0x65, 0xeb, 0xbd, 0x77,
	0xfd, 0xa9, 0xf4, 0xfe, 0x92, 0x27, 0x10, 0xbe, 0x03, 0xea, 0x10, 0x9a, 0xba, 0xce, 0xc6, 0x98,
	0x1f, 0xc7, 0x78, 0xdc, 0x53, 0x7a, 0xe3, 0x00, 0x2a, 0xdf, 0x68, 0x82, 0x3e, 0x1f, 0xa1, 0x7c,
	0x3c, 0x8f, 0x62, 0x1f, 0xd6, 0x09, 0xc8, 0x7d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xe7, 0xa3,
	0x9e, 0x97, 0x03, 0x00, 0x00,
}
