// Code generated by protoc-gen-go.
// source: conf.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 获取游戏全局配置数据
type CConfig struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=4000" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CConfig) Reset()                    { *m = CConfig{} }
func (m *CConfig) String() string            { return proto.CompactTextString(m) }
func (*CConfig) ProtoMessage()               {}
func (*CConfig) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

const Default_CConfig_Code uint32 = 4000

func (m *CConfig) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CConfig_Code
}

type SConfig struct {
	Code             *uint32          `protobuf:"varint,1,opt,name=code,def=4000" json:"code,omitempty"`
	Room             []*RoomAttrube   `protobuf:"bytes,2,rep,name=room" json:"room,omitempty"`
	Circle           []*CircleAttrube `protobuf:"bytes,3,rep,name=circle" json:"circle,omitempty"`
	Sys              *SysConfig       `protobuf:"bytes,4,req,name=sys" json:"sys,omitempty"`
	Match            []*MatchAttrube  `protobuf:"bytes,5,rep,name=match" json:"match,omitempty"`
	Error            *uint32          `protobuf:"varint,6,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SConfig) Reset()                    { *m = SConfig{} }
func (m *SConfig) String() string            { return proto.CompactTextString(m) }
func (*SConfig) ProtoMessage()               {}
func (*SConfig) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

const Default_SConfig_Code uint32 = 4000
const Default_SConfig_Error uint32 = 0

func (m *SConfig) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SConfig_Code
}

func (m *SConfig) GetRoom() []*RoomAttrube {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *SConfig) GetCircle() []*CircleAttrube {
	if m != nil {
		return m.Circle
	}
	return nil
}

func (m *SConfig) GetSys() *SysConfig {
	if m != nil {
		return m.Sys
	}
	return nil
}

func (m *SConfig) GetMatch() []*MatchAttrube {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *SConfig) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SConfig_Error
}

// 系统配置
type SysConfig struct {
	Imageserver      *string `protobuf:"bytes,1,req,name=imageserver" json:"imageserver,omitempty"`
	Discardtimeout   *uint32 `protobuf:"varint,2,req,name=discardtimeout" json:"discardtimeout,omitempty"`
	Version          *string `protobuf:"bytes,3,req,name=version" json:"version,omitempty"`
	Feedbackserver   *string `protobuf:"bytes,4,req,name=feedbackserver" json:"feedbackserver,omitempty"`
	Shareaddr        *string `protobuf:"bytes,5,req,name=shareaddr" json:"shareaddr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SysConfig) Reset()                    { *m = SysConfig{} }
func (m *SysConfig) String() string            { return proto.CompactTextString(m) }
func (*SysConfig) ProtoMessage()               {}
func (*SysConfig) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *SysConfig) GetImageserver() string {
	if m != nil && m.Imageserver != nil {
		return *m.Imageserver
	}
	return ""
}

func (m *SysConfig) GetDiscardtimeout() uint32 {
	if m != nil && m.Discardtimeout != nil {
		return *m.Discardtimeout
	}
	return 0
}

func (m *SysConfig) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *SysConfig) GetFeedbackserver() string {
	if m != nil && m.Feedbackserver != nil {
		return *m.Feedbackserver
	}
	return ""
}

func (m *SysConfig) GetShareaddr() string {
	if m != nil && m.Shareaddr != nil {
		return *m.Shareaddr
	}
	return ""
}

func init() {
	proto.RegisterType((*CConfig)(nil), "protocol.CConfig")
	proto.RegisterType((*SConfig)(nil), "protocol.SConfig")
	proto.RegisterType((*SysConfig)(nil), "protocol.SysConfig")
}

var fileDescriptor3 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x8e, 0xcb, 0x6a, 0x02, 0x31,
	0x14, 0x86, 0x99, 0x9b, 0x97, 0x23, 0xf6, 0x12, 0xa9, 0x0d, 0x85, 0x42, 0xb0, 0x94, 0xce, 0x4a,
	0x06, 0xe9, 0xaa, 0xbb, 0xe2, 0xba, 0x9b, 0xfa, 0x04, 0x31, 0x39, 0x6a, 0xa8, 0xe3, 0x29, 0x27,
	0x71, 0xc0, 0x17, 0xec, 0x73, 0x15, 0x53, 0x87, 0x59, 0x75, 0x15, 0xf8, 0xf2, 0xf1, 0x9d, 0x1f,
	0xc0, 0xd0, 0x61, 0x33, 0xff, 0x66, 0x0a, 0x24, 0x06, 0xf1, 0x31, 0xb4, 0x7f, 0x18, 0x34, 0xf4,
	0xc7, 0x66, 0x8f, 0xd0, 0x5f, 0x2e, 0xe9, 0xb0, 0x71, 0x5b, 0x21, 0x20, 0x37, 0x64, 0x51, 0x26,
	0x2a, 0x29, 0xc7, 0x6f, 0xf9, 0x6b, 0x55, 0x55, 0xb3, 0x9f, 0x04, 0xfa, 0xab, 0xff, 0xff, 0xc5,
	0x13, 0xe4, 0x4c, 0x54, 0xcb, 0x54, 0x65, 0xe5, 0x68, 0x71, 0x37, 0x6f, 0x2f, 0xcc, 0x3f, 0x89,
	0xea, 0xf7, 0x10, 0xf8, 0xb8, 0x46, 0xf1, 0x02, 0x3d, 0xe3, 0xd8, 0xec, 0x51, 0x66, 0x51, 0xbb,
	0xef, 0xb4, 0x65, 0xe4, 0xad, 0xa8, 0x20, 0xf3, 0x27, 0x2f, 0x73, 0x95, 0x96, 0xa3, 0xc5, 0xa4,
	0xb3, 0x56, 0x27, 0x7f, 0xd9, 0xf0, 0x0c, 0x45, 0xad, 0x83, 0xd9, 0xc9, 0x22, 0x96, 0xa6, 0x9d,
	0xf3, 0x71, 0xc6, 0x6d, 0xe8, 0x06, 0x0a, 0x64, 0x26, 0x96, 0xbd, 0xb8, 0x35, 0xa9, 0x66, 0x01,
	0x86, 0x5d, 0x65, 0x02, 0x23, 0x57, 0xeb, 0x2d, 0x7a, 0xe4, 0x06, 0x59, 0x26, 0x2a, 0x2d, 0x87,
	0x62, 0x0a, 0x57, 0xd6, 0x79, 0xa3, 0xd9, 0x06, 0x57, 0x23, 0x1d, 0x83, 0x4c, 0x55, 0x5a, 0x8e,
	0xc5, 0x35, 0xf4, 0x1b, 0x64, 0xef, 0xe8, 0x20, 0xb3, 0x56, 0xdc, 0x20, 0xda, 0xb5, 0x36, 0x5f,
	0x97, 0x40, 0x1e, 0xf9, 0x2d, 0x0c, 0xfd, 0x4e, 0x33, 0x6a, 0x6b, 0x59, 0x16, 0x67, 0xf4, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xeb, 0x54, 0xa5, 0x33, 0x7e, 0x01, 0x00, 0x00,
}
