// Code generated by protoc-gen-go.
// source: sys.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CPing struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9000" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPing) Reset()                    { *m = CPing{} }
func (m *CPing) String() string            { return proto.CompactTextString(m) }
func (*CPing) ProtoMessage()               {}
func (*CPing) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

const Default_CPing_Code uint32 = 9000

func (m *CPing) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CPing_Code
}

type SPing struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9000" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SPing) Reset()                    { *m = SPing{} }
func (m *SPing) String() string            { return proto.CompactTextString(m) }
func (*SPing) ProtoMessage()               {}
func (*SPing) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

const Default_SPing_Code uint32 = 9000
const Default_SPing_Error uint32 = 0

func (m *SPing) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SPing_Code
}

func (m *SPing) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SPing_Error
}

type CFeedback struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9002" json:"code,omitempty"`
	Content          *string `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	Kind             *uint32 `protobuf:"varint,3,req,name=kind" json:"kind,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CFeedback) Reset()                    { *m = CFeedback{} }
func (m *CFeedback) String() string            { return proto.CompactTextString(m) }
func (*CFeedback) ProtoMessage()               {}
func (*CFeedback) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{2} }

const Default_CFeedback_Code uint32 = 9002

func (m *CFeedback) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CFeedback_Code
}

func (m *CFeedback) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *CFeedback) GetKind() uint32 {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return 0
}

type SFeedback struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9002" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SFeedback) Reset()                    { *m = SFeedback{} }
func (m *SFeedback) String() string            { return proto.CompactTextString(m) }
func (*SFeedback) ProtoMessage()               {}
func (*SFeedback) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{3} }

const Default_SFeedback_Code uint32 = 9002
const Default_SFeedback_Error uint32 = 0

func (m *SFeedback) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SFeedback_Code
}

func (m *SFeedback) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SFeedback_Error
}

// 公告
type CNotice struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9003" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CNotice) Reset()                    { *m = CNotice{} }
func (m *CNotice) String() string            { return proto.CompactTextString(m) }
func (*CNotice) ProtoMessage()               {}
func (*CNotice) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{4} }

const Default_CNotice_Code uint32 = 9003

func (m *CNotice) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CNotice_Code
}

// 公告
type SNotice struct {
	Code             *uint32   `protobuf:"varint,1,opt,name=code,def=9003" json:"code,omitempty"`
	List             []*Notice `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32   `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SNotice) Reset()                    { *m = SNotice{} }
func (m *SNotice) String() string            { return proto.CompactTextString(m) }
func (*SNotice) ProtoMessage()               {}
func (*SNotice) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{5} }

const Default_SNotice_Code uint32 = 9003
const Default_SNotice_Error uint32 = 0

func (m *SNotice) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SNotice_Code
}

func (m *SNotice) GetList() []*Notice {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SNotice) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SNotice_Error
}

// 公告
type Notice struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Title            *string `protobuf:"bytes,3,req,name=title" json:"title,omitempty"`
	Content          *string `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	Time             *uint32 `protobuf:"varint,5,req,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Notice) Reset()                    { *m = Notice{} }
func (m *Notice) String() string            { return proto.CompactTextString(m) }
func (*Notice) ProtoMessage()               {}
func (*Notice) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{6} }

func (m *Notice) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Notice) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Notice) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Notice) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Notice) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

// 商城
type CBuy struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9006" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBuy) Reset()                    { *m = CBuy{} }
func (m *CBuy) String() string            { return proto.CompactTextString(m) }
func (*CBuy) ProtoMessage()               {}
func (*CBuy) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{7} }

const Default_CBuy_Code uint32 = 9006

func (m *CBuy) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBuy_Code
}

func (m *CBuy) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SBuy struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9006" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBuy) Reset()                    { *m = SBuy{} }
func (m *SBuy) String() string            { return proto.CompactTextString(m) }
func (*SBuy) ProtoMessage()               {}
func (*SBuy) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{8} }

const Default_SBuy_Code uint32 = 9006
const Default_SBuy_Error uint32 = 0

func (m *SBuy) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBuy_Code
}

func (m *SBuy) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SBuy) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBuy_Error
}

// 绑定玩家id
type CBuild struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9007" json:"code,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CBuild) Reset()                    { *m = CBuild{} }
func (m *CBuild) String() string            { return proto.CompactTextString(m) }
func (*CBuild) ProtoMessage()               {}
func (*CBuild) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{9} }

const Default_CBuild_Code uint32 = 9007

func (m *CBuild) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CBuild_Code
}

func (m *CBuild) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type SBuild struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9007" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SBuild) Reset()                    { *m = SBuild{} }
func (m *SBuild) String() string            { return proto.CompactTextString(m) }
func (*SBuild) ProtoMessage()               {}
func (*SBuild) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{10} }

const Default_SBuild_Code uint32 = 9007
const Default_SBuild_Error uint32 = 0

func (m *SBuild) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SBuild_Code
}

func (m *SBuild) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SBuild) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SBuild_Error
}

// 获取活动列表
type CActivity struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9010" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CActivity) Reset()                    { *m = CActivity{} }
func (m *CActivity) String() string            { return proto.CompactTextString(m) }
func (*CActivity) ProtoMessage()               {}
func (*CActivity) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{11} }

const Default_CActivity_Code uint32 = 9010

func (m *CActivity) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CActivity_Code
}

type ProtoActivity struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Count            *uint32 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	Rewards          *uint32 `protobuf:"varint,4,req,name=rewards" json:"rewards,omitempty"`
	Starttime        *uint32 `protobuf:"varint,5,req,name=starttime" json:"starttime,omitempty"`
	Endtime          *uint32 `protobuf:"varint,6,req,name=endtime" json:"endtime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoActivity) Reset()                    { *m = ProtoActivity{} }
func (m *ProtoActivity) String() string            { return proto.CompactTextString(m) }
func (*ProtoActivity) ProtoMessage()               {}
func (*ProtoActivity) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{12} }

func (m *ProtoActivity) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoActivity) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ProtoActivity) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ProtoActivity) GetRewards() uint32 {
	if m != nil && m.Rewards != nil {
		return *m.Rewards
	}
	return 0
}

func (m *ProtoActivity) GetStarttime() uint32 {
	if m != nil && m.Starttime != nil {
		return *m.Starttime
	}
	return 0
}

func (m *ProtoActivity) GetEndtime() uint32 {
	if m != nil && m.Endtime != nil {
		return *m.Endtime
	}
	return 0
}

type SActivity struct {
	Code             *uint32          `protobuf:"varint,1,opt,name=code,def=9010" json:"code,omitempty"`
	List             []*ProtoActivity `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32          `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SActivity) Reset()                    { *m = SActivity{} }
func (m *SActivity) String() string            { return proto.CompactTextString(m) }
func (*SActivity) ProtoMessage()               {}
func (*SActivity) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{13} }

const Default_SActivity_Code uint32 = 9010
const Default_SActivity_Error uint32 = 0

func (m *SActivity) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SActivity_Code
}

func (m *SActivity) GetList() []*ProtoActivity {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SActivity) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SActivity_Error
}

// 活动领奖
type CGetActivityRewards struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9011" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGetActivityRewards) Reset()                    { *m = CGetActivityRewards{} }
func (m *CGetActivityRewards) String() string            { return proto.CompactTextString(m) }
func (*CGetActivityRewards) ProtoMessage()               {}
func (*CGetActivityRewards) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{14} }

const Default_CGetActivityRewards_Code uint32 = 9011

func (m *CGetActivityRewards) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CGetActivityRewards_Code
}

func (m *CGetActivityRewards) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SGetActivityRewards struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9011" json:"code,omitempty"`
	Error            *uint32 `protobuf:"varint,2,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SGetActivityRewards) Reset()                    { *m = SGetActivityRewards{} }
func (m *SGetActivityRewards) String() string            { return proto.CompactTextString(m) }
func (*SGetActivityRewards) ProtoMessage()               {}
func (*SGetActivityRewards) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{15} }

const Default_SGetActivityRewards_Code uint32 = 9011
const Default_SGetActivityRewards_Error uint32 = 0

func (m *SGetActivityRewards) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SGetActivityRewards_Code
}

func (m *SGetActivityRewards) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SGetActivityRewards_Error
}

// 更新活动
type SUpdateActivity struct {
	Code             *uint32          `protobuf:"varint,1,opt,name=code,def=9012" json:"code,omitempty"`
	List             []*ProtoActivity `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SUpdateActivity) Reset()                    { *m = SUpdateActivity{} }
func (m *SUpdateActivity) String() string            { return proto.CompactTextString(m) }
func (*SUpdateActivity) ProtoMessage()               {}
func (*SUpdateActivity) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{16} }

const Default_SUpdateActivity_Code uint32 = 9012

func (m *SUpdateActivity) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SUpdateActivity_Code
}

func (m *SUpdateActivity) GetList() []*ProtoActivity {
	if m != nil {
		return m.List
	}
	return nil
}

// 分享邀请好友活动
type CWechatShare struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9013" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWechatShare) Reset()                    { *m = CWechatShare{} }
func (m *CWechatShare) String() string            { return proto.CompactTextString(m) }
func (*CWechatShare) ProtoMessage()               {}
func (*CWechatShare) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{17} }

const Default_CWechatShare_Code uint32 = 9013

func (m *CWechatShare) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWechatShare_Code
}

// 兑换
type CTradeList struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9020" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTradeList) Reset()                    { *m = CTradeList{} }
func (m *CTradeList) String() string            { return proto.CompactTextString(m) }
func (*CTradeList) ProtoMessage()               {}
func (*CTradeList) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{18} }

const Default_CTradeList_Code uint32 = 9020

func (m *CTradeList) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTradeList_Code
}

type STradeList struct {
	Code             *uint32       `protobuf:"varint,1,opt,name=code,def=9020" json:"code,omitempty"`
	List             []*ProtoTrade `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32       `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *STradeList) Reset()                    { *m = STradeList{} }
func (m *STradeList) String() string            { return proto.CompactTextString(m) }
func (*STradeList) ProtoMessage()               {}
func (*STradeList) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{19} }

const Default_STradeList_Code uint32 = 9020
const Default_STradeList_Error uint32 = 0

func (m *STradeList) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STradeList_Code
}

func (m *STradeList) GetList() []*ProtoTrade {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *STradeList) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STradeList_Error
}

type ProtoTrade struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Count            *uint32 `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoTrade) Reset()                    { *m = ProtoTrade{} }
func (m *ProtoTrade) String() string            { return proto.CompactTextString(m) }
func (*ProtoTrade) ProtoMessage()               {}
func (*ProtoTrade) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{20} }

func (m *ProtoTrade) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTrade) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type CTradeRecord struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9021" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTradeRecord) Reset()                    { *m = CTradeRecord{} }
func (m *CTradeRecord) String() string            { return proto.CompactTextString(m) }
func (*CTradeRecord) ProtoMessage()               {}
func (*CTradeRecord) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{21} }

const Default_CTradeRecord_Code uint32 = 9021

func (m *CTradeRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTradeRecord_Code
}

type STradeRecord struct {
	Code             *uint32             `protobuf:"varint,1,opt,name=code,def=9021" json:"code,omitempty"`
	List             []*ProtoTradeRecard `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error            *uint32             `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *STradeRecord) Reset()                    { *m = STradeRecord{} }
func (m *STradeRecord) String() string            { return proto.CompactTextString(m) }
func (*STradeRecord) ProtoMessage()               {}
func (*STradeRecord) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{22} }

const Default_STradeRecord_Code uint32 = 9021
const Default_STradeRecord_Error uint32 = 0

func (m *STradeRecord) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STradeRecord_Code
}

func (m *STradeRecord) GetList() []*ProtoTradeRecard {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *STradeRecord) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STradeRecord_Error
}

type ProtoTradeRecard struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Time             *uint32 `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoTradeRecard) Reset()                    { *m = ProtoTradeRecard{} }
func (m *ProtoTradeRecard) String() string            { return proto.CompactTextString(m) }
func (*ProtoTradeRecard) ProtoMessage()               {}
func (*ProtoTradeRecard) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{23} }

func (m *ProtoTradeRecard) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTradeRecard) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

type CTradeUserInfo struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9022" json:"code,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Phone            *string `protobuf:"bytes,3,req,name=phone" json:"phone,omitempty"`
	Address          *string `protobuf:"bytes,4,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTradeUserInfo) Reset()                    { *m = CTradeUserInfo{} }
func (m *CTradeUserInfo) String() string            { return proto.CompactTextString(m) }
func (*CTradeUserInfo) ProtoMessage()               {}
func (*CTradeUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{24} }

const Default_CTradeUserInfo_Code uint32 = 9022

func (m *CTradeUserInfo) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTradeUserInfo_Code
}

func (m *CTradeUserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CTradeUserInfo) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *CTradeUserInfo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type STradeUserInfo struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9022" json:"code,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Phone            *string `protobuf:"bytes,3,req,name=phone" json:"phone,omitempty"`
	Address          *string `protobuf:"bytes,4,req,name=address" json:"address,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STradeUserInfo) Reset()                    { *m = STradeUserInfo{} }
func (m *STradeUserInfo) String() string            { return proto.CompactTextString(m) }
func (*STradeUserInfo) ProtoMessage()               {}
func (*STradeUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{25} }

const Default_STradeUserInfo_Code uint32 = 9022
const Default_STradeUserInfo_Error uint32 = 0

func (m *STradeUserInfo) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STradeUserInfo_Code
}

func (m *STradeUserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *STradeUserInfo) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *STradeUserInfo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *STradeUserInfo) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STradeUserInfo_Error
}

type CTrade struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9023" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTrade) Reset()                    { *m = CTrade{} }
func (m *CTrade) String() string            { return proto.CompactTextString(m) }
func (*CTrade) ProtoMessage()               {}
func (*CTrade) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{26} }

const Default_CTrade_Code uint32 = 9023

func (m *CTrade) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTrade_Code
}

func (m *CTrade) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type STrade struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9023" json:"code,omitempty"`
	Result           *uint32 `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Id               *uint32 `protobuf:"varint,3,req,name=id" json:"id,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STrade) Reset()                    { *m = STrade{} }
func (m *STrade) String() string            { return proto.CompactTextString(m) }
func (*STrade) ProtoMessage()               {}
func (*STrade) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{27} }

const Default_STrade_Code uint32 = 9023
const Default_STrade_Error uint32 = 0

func (m *STrade) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STrade_Code
}

func (m *STrade) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *STrade) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *STrade) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STrade_Error
}

// 爱贝支付 - 下单
type CIapppayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9050" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CIapppayOrder) Reset()                    { *m = CIapppayOrder{} }
func (m *CIapppayOrder) String() string            { return proto.CompactTextString(m) }
func (*CIapppayOrder) ProtoMessage()               {}
func (*CIapppayOrder) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{28} }

const Default_CIapppayOrder_Code uint32 = 9050

func (m *CIapppayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CIapppayOrder_Code
}

func (m *CIapppayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SIapppayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9050" json:"code,omitempty"`
	Transid          *string `protobuf:"bytes,2,req,name=transid" json:"transid,omitempty"`
	Id               *uint32 `protobuf:"varint,3,req,name=id" json:"id,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SIapppayOrder) Reset()                    { *m = SIapppayOrder{} }
func (m *SIapppayOrder) String() string            { return proto.CompactTextString(m) }
func (*SIapppayOrder) ProtoMessage()               {}
func (*SIapppayOrder) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{29} }

const Default_SIapppayOrder_Code uint32 = 9050
const Default_SIapppayOrder_Error uint32 = 0

func (m *SIapppayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SIapppayOrder_Code
}

func (m *SIapppayOrder) GetTransid() string {
	if m != nil && m.Transid != nil {
		return *m.Transid
	}
	return ""
}

func (m *SIapppayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SIapppayOrder) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SIapppayOrder_Error
}

//  苹果支付
type CApplePay struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9052" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Receipt          *string `protobuf:"bytes,3,req,name=receipt" json:"receipt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CApplePay) Reset()                    { *m = CApplePay{} }
func (m *CApplePay) String() string            { return proto.CompactTextString(m) }
func (*CApplePay) ProtoMessage()               {}
func (*CApplePay) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{30} }

const Default_CApplePay_Code uint32 = 9052

func (m *CApplePay) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CApplePay_Code
}

func (m *CApplePay) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CApplePay) GetReceipt() string {
	if m != nil && m.Receipt != nil {
		return *m.Receipt
	}
	return ""
}

type SApplePay struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9052" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Error            *uint32 `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SApplePay) Reset()                    { *m = SApplePay{} }
func (m *SApplePay) String() string            { return proto.CompactTextString(m) }
func (*SApplePay) ProtoMessage()               {}
func (*SApplePay) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{31} }

const Default_SApplePay_Code uint32 = 9052
const Default_SApplePay_Error uint32 = 0

func (m *SApplePay) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SApplePay_Code
}

func (m *SApplePay) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SApplePay) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SApplePay_Error
}

// 微信支付 - 下单
type CWxpayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9053" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Body             *string `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWxpayOrder) Reset()                    { *m = CWxpayOrder{} }
func (m *CWxpayOrder) String() string            { return proto.CompactTextString(m) }
func (*CWxpayOrder) ProtoMessage()               {}
func (*CWxpayOrder) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{32} }

const Default_CWxpayOrder_Code uint32 = 9053

func (m *CWxpayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWxpayOrder_Code
}

func (m *CWxpayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CWxpayOrder) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

type SWxpayOrder struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9053" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Payreq           *string `protobuf:"bytes,3,req,name=payreq" json:"payreq,omitempty"`
	Orderid          *string `protobuf:"bytes,4,req,name=orderid" json:"orderid,omitempty"`
	Error            *uint32 `protobuf:"varint,5,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SWxpayOrder) Reset()                    { *m = SWxpayOrder{} }
func (m *SWxpayOrder) String() string            { return proto.CompactTextString(m) }
func (*SWxpayOrder) ProtoMessage()               {}
func (*SWxpayOrder) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{33} }

const Default_SWxpayOrder_Code uint32 = 9053
const Default_SWxpayOrder_Error uint32 = 0

func (m *SWxpayOrder) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SWxpayOrder_Code
}

func (m *SWxpayOrder) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SWxpayOrder) GetPayreq() string {
	if m != nil && m.Payreq != nil {
		return *m.Payreq
	}
	return ""
}

func (m *SWxpayOrder) GetOrderid() string {
	if m != nil && m.Orderid != nil {
		return *m.Orderid
	}
	return ""
}

func (m *SWxpayOrder) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SWxpayOrder_Error
}

// 微信支付 - 查询
type CWxpayQuery struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9054" json:"code,omitempty"`
	Transid          *string `protobuf:"bytes,2,req,name=transid" json:"transid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWxpayQuery) Reset()                    { *m = CWxpayQuery{} }
func (m *CWxpayQuery) String() string            { return proto.CompactTextString(m) }
func (*CWxpayQuery) ProtoMessage()               {}
func (*CWxpayQuery) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{34} }

const Default_CWxpayQuery_Code uint32 = 9054

func (m *CWxpayQuery) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CWxpayQuery_Code
}

func (m *CWxpayQuery) GetTransid() string {
	if m != nil && m.Transid != nil {
		return *m.Transid
	}
	return ""
}

type SWxpayQuery struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=9054" json:"code,omitempty"`
	Orderid          *string `protobuf:"bytes,2,req,name=orderid" json:"orderid,omitempty"`
	Result           *uint32 `protobuf:"varint,3,req,name=result" json:"result,omitempty"`
	Error            *uint32 `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SWxpayQuery) Reset()                    { *m = SWxpayQuery{} }
func (m *SWxpayQuery) String() string            { return proto.CompactTextString(m) }
func (*SWxpayQuery) ProtoMessage()               {}
func (*SWxpayQuery) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{35} }

const Default_SWxpayQuery_Code uint32 = 9054
const Default_SWxpayQuery_Error uint32 = 0

func (m *SWxpayQuery) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SWxpayQuery_Code
}

func (m *SWxpayQuery) GetOrderid() string {
	if m != nil && m.Orderid != nil {
		return *m.Orderid
	}
	return ""
}

func (m *SWxpayQuery) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SWxpayQuery) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SWxpayQuery_Error
}

func init() {
	proto.RegisterType((*CPing)(nil), "protocol.CPing")
	proto.RegisterType((*SPing)(nil), "protocol.SPing")
	proto.RegisterType((*CFeedback)(nil), "protocol.CFeedback")
	proto.RegisterType((*SFeedback)(nil), "protocol.SFeedback")
	proto.RegisterType((*CNotice)(nil), "protocol.CNotice")
	proto.RegisterType((*SNotice)(nil), "protocol.SNotice")
	proto.RegisterType((*Notice)(nil), "protocol.Notice")
	proto.RegisterType((*CBuy)(nil), "protocol.CBuy")
	proto.RegisterType((*SBuy)(nil), "protocol.SBuy")
	proto.RegisterType((*CBuild)(nil), "protocol.CBuild")
	proto.RegisterType((*SBuild)(nil), "protocol.SBuild")
	proto.RegisterType((*CActivity)(nil), "protocol.CActivity")
	proto.RegisterType((*ProtoActivity)(nil), "protocol.ProtoActivity")
	proto.RegisterType((*SActivity)(nil), "protocol.SActivity")
	proto.RegisterType((*CGetActivityRewards)(nil), "protocol.CGetActivityRewards")
	proto.RegisterType((*SGetActivityRewards)(nil), "protocol.SGetActivityRewards")
	proto.RegisterType((*SUpdateActivity)(nil), "protocol.SUpdateActivity")
	proto.RegisterType((*CWechatShare)(nil), "protocol.CWechatShare")
	proto.RegisterType((*CTradeList)(nil), "protocol.CTradeList")
	proto.RegisterType((*STradeList)(nil), "protocol.STradeList")
	proto.RegisterType((*ProtoTrade)(nil), "protocol.ProtoTrade")
	proto.RegisterType((*CTradeRecord)(nil), "protocol.CTradeRecord")
	proto.RegisterType((*STradeRecord)(nil), "protocol.STradeRecord")
	proto.RegisterType((*ProtoTradeRecard)(nil), "protocol.ProtoTradeRecard")
	proto.RegisterType((*CTradeUserInfo)(nil), "protocol.CTradeUserInfo")
	proto.RegisterType((*STradeUserInfo)(nil), "protocol.STradeUserInfo")
	proto.RegisterType((*CTrade)(nil), "protocol.CTrade")
	proto.RegisterType((*STrade)(nil), "protocol.STrade")
	proto.RegisterType((*CIapppayOrder)(nil), "protocol.CIapppayOrder")
	proto.RegisterType((*SIapppayOrder)(nil), "protocol.SIapppayOrder")
	proto.RegisterType((*CApplePay)(nil), "protocol.CApplePay")
	proto.RegisterType((*SApplePay)(nil), "protocol.SApplePay")
	proto.RegisterType((*CWxpayOrder)(nil), "protocol.CWxpayOrder")
	proto.RegisterType((*SWxpayOrder)(nil), "protocol.SWxpayOrder")
	proto.RegisterType((*CWxpayQuery)(nil), "protocol.CWxpayQuery")
	proto.RegisterType((*SWxpayQuery)(nil), "protocol.SWxpayQuery")
}

var fileDescriptor11 = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xef, 0x4f, 0xd3, 0x40,
	0x18, 0x0e, 0x5b, 0xb7, 0xd9, 0x17, 0x3a, 0xb0, 0x98, 0xb8, 0x68, 0xd4, 0xe5, 0x12, 0x75, 0x1f,
	0x14, 0xbb, 0x22, 0x1a, 0x05, 0x49, 0xa4, 0x89, 0x06, 0x43, 0x64, 0xee, 0x40, 0xfc, 0x64, 0x3c,
	0x7a, 0xa7, 0x34, 0x8c, 0x5e, 0xbd, 0xde, 0xd4, 0xfd, 0xf7, 0xe6, 0xda, 0x95, 0xb5, 0xf4, 0xba,
	0x61, 0xe2, 0xa7, 0x25, 0xbb, 0xf7, 0xb9, 0xe7, 0xc7, 0x3d, 0x7d, 0xc1, 0x8c, 0x27, 0xf1, 0x46,
	0x24, 0xb8, 0xe4, 0xf6, 0x8d, 0xe4, 0xc7, 0xe7, 0x23, 0x74, 0x17, 0x1a, 0xde, 0x20, 0x08, 0x7f,
	0xd8, 0x36, 0x18, 0x3e, 0xa7, 0xac, 0xb3, 0xd4, 0x5d, 0xea, 0x59, 0xaf, 0x8d, 0x57, 0x8e, 0xe3,
	0xa0, 0xa7, 0xd0, 0xc0, 0x55, 0x87, 0xf6, 0x1a, 0x34, 0x98, 0x10, 0x5c, 0x74, 0x6a, 0xc9, 0x9f,
	0x4b, 0x0e, 0xda, 0x05, 0xd3, 0x7b, 0xc7, 0x18, 0x3d, 0x25, 0xfe, 0xb9, 0x06, 0xe2, 0xda, 0xab,
	0xd0, 0xf2, 0x79, 0x28, 0x59, 0x28, 0x3b, 0xb5, 0x6e, 0xad, 0x67, 0xda, 0x2b, 0x60, 0x9c, 0x07,
	0x21, 0xed, 0xd4, 0xbb, 0xb5, 0x9e, 0x85, 0xfa, 0x60, 0xe2, 0xb9, 0xf8, 0x32, 0xe5, 0x3d, 0x68,
	0x79, 0x1f, 0xb9, 0x0c, 0x7c, 0xa6, 0x01, 0x6c, 0xa2, 0x43, 0x68, 0xe1, 0xea, 0x63, 0xfb, 0x3e,
	0x18, 0xa3, 0x20, 0x56, 0x62, 0xea, 0xbd, 0x65, 0x77, 0x6d, 0x23, 0x4b, 0x65, 0x63, 0x8a, 0xb9,
	0xe4, 0xab, 0x67, 0x7c, 0x03, 0x68, 0x4e, 0xcf, 0x00, 0x6a, 0x01, 0x4d, 0x6f, 0x53, 0x36, 0xe4,
	0x24, 0x62, 0x89, 0x29, 0xcb, 0xb6, 0xa0, 0x21, 0x03, 0x39, 0x62, 0x89, 0x2b, 0x33, 0x6f, 0xda,
	0xc8, 0x4c, 0xcb, 0xe0, 0x82, 0x75, 0x1a, 0x89, 0xe9, 0x47, 0x60, 0x78, 0x7b, 0xe3, 0x89, 0x46,
	0xdf, 0x8b, 0x29, 0x47, 0x72, 0x2b, 0xda, 0x01, 0x03, 0x57, 0xcd, 0xb5, 0xa1, 0x29, 0x58, 0x3c,
	0x1e, 0xc9, 0xa9, 0x82, 0xb2, 0xee, 0x1e, 0x34, 0xbd, 0xbd, 0x71, 0x30, 0xa2, 0x1a, 0xfc, 0xcb,
	0x1c, 0x8f, 0x89, 0x76, 0xa1, 0x89, 0xab, 0x27, 0x17, 0x33, 0x3d, 0x00, 0xd3, 0x7b, 0xeb, 0xcb,
	0xe0, 0x57, 0x20, 0x35, 0x62, 0xfb, 0x0e, 0xba, 0x00, 0x6b, 0xa0, 0x72, 0xbe, 0x1c, 0xca, 0x92,
	0xac, 0xe9, 0x92, 0xf4, 0xf9, 0x38, 0x94, 0x69, 0x3f, 0x54, 0x92, 0x82, 0xfd, 0x26, 0x82, 0xc6,
	0x49, 0x92, 0x96, 0x7d, 0x13, 0xcc, 0x58, 0x12, 0x21, 0x67, 0x71, 0xaa, 0x19, 0x16, 0xd2, 0xe4,
	0x8f, 0x66, 0x92, 0xdb, 0x17, 0x30, 0xf1, 0x3c, 0x3d, 0xf6, 0xc3, 0x42, 0x09, 0x6e, 0xcf, 0x4a,
	0x50, 0x54, 0x59, 0x76, 0xba, 0x05, 0xeb, 0xde, 0x7b, 0x26, 0xb3, 0x89, 0x61, 0x2a, 0x4d, 0xc3,
	0xd1, 0x2f, 0x3c, 0xe4, 0x36, 0xac, 0xe3, 0x6b, 0xc2, 0xca, 0x7d, 0x3f, 0x80, 0x55, 0x7c, 0x1c,
	0x51, 0x22, 0xd9, 0x1c, 0x4f, 0xee, 0x35, 0x3d, 0x21, 0x04, 0x2b, 0xde, 0x09, 0xf3, 0xcf, 0x88,
	0xc4, 0x67, 0x44, 0x68, 0xbe, 0x91, 0xfe, 0x26, 0xea, 0x02, 0x78, 0x47, 0x82, 0x50, 0x76, 0x10,
	0xc4, 0xb2, 0x3c, 0xe1, 0x3a, 0xe8, 0x33, 0x00, 0x9e, 0x3b, 0x61, 0xa3, 0x82, 0x9c, 0x5b, 0x57,
	0xe4, 0x24, 0x58, 0x4d, 0xbe, 0x8f, 0x01, 0x72, 0xe7, 0xf9, 0x96, 0x5c, 0xf6, 0x22, 0x4d, 0x54,
	0xd9, 0x48, 0x86, 0x86, 0xcc, 0xe7, 0x42, 0x53, 0x5c, 0xb7, 0x8f, 0xbe, 0xc2, 0x0a, 0x5e, 0x30,
	0x63, 0xf7, 0x0a, 0x32, 0xef, 0xe8, 0x64, 0x0e, 0x99, 0x4f, 0x04, 0xd5, 0x88, 0x7d, 0x02, 0x6b,
	0xa5, 0xa9, 0xab, 0xc5, 0x56, 0xa5, 0x4c, 0x15, 0x0f, 0xa1, 0x9d, 0x2a, 0x3e, 0x8e, 0x99, 0xd8,
	0x0f, 0xbf, 0x73, 0x8d, 0x1e, 0x57, 0x61, 0x42, 0x32, 0xc5, 0x98, 0xca, 0x74, 0x74, 0xc6, 0xc3,
	0xdc, 0x5a, 0x21, 0x94, 0x0a, 0x16, 0xa7, 0x1f, 0x83, 0x89, 0x28, 0xb4, 0xf1, 0x7f, 0xbe, 0x73,
	0xe6, 0xb3, 0x91, 0x5f, 0x24, 0xe9, 0x83, 0x94, 0x6f, 0xdf, 0x2c, 0xf4, 0xfc, 0x03, 0x34, 0x71,
	0xf5, 0xe4, 0xd5, 0x45, 0x92, 0x22, 0xeb, 0xc5, 0xa5, 0x62, 0x64, 0xac, 0xcf, 0xc0, 0xf2, 0xf6,
	0x49, 0x14, 0x45, 0x64, 0x72, 0x28, 0x28, 0x13, 0xe5, 0x2b, 0xb7, 0x9c, 0x02, 0xf9, 0x10, 0x2c,
	0xbc, 0x10, 0xb0, 0x0a, 0x2d, 0x29, 0x48, 0x18, 0x67, 0xbb, 0x6f, 0x81, 0x88, 0x1d, 0xb5, 0xd9,
	0xa2, 0x68, 0xc4, 0x06, 0x44, 0xf3, 0xd5, 0x6d, 0xb9, 0x79, 0x01, 0xe9, 0xae, 0xf2, 0x59, 0x10,
	0xa5, 0xcb, 0xcb, 0x44, 0x6f, 0xd4, 0x1e, 0xba, 0x2e, 0xba, 0xdc, 0xaf, 0x6d, 0x58, 0xf6, 0x4e,
	0xfe, 0xcc, 0xb1, 0x53, 0x08, 0x5f, 0x3d, 0xf3, 0x29, 0xa7, 0x93, 0x29, 0xf7, 0x37, 0x58, 0xc6,
	0xff, 0x00, 0x6e, 0x43, 0x33, 0x22, 0x13, 0xc1, 0x7e, 0xce, 0x6a, 0xc1, 0x15, 0x30, 0xa0, 0x95,
	0xb5, 0x70, 0x33, 0x79, 0x9f, 0xc6, 0x4c, 0xe8, 0xfc, 0x3d, 0x2f, 0xa5, 0x8d, 0x8e, 0x32, 0x55,
	0x73, 0x31, 0x19, 0x73, 0xfa, 0x42, 0xb3, 0xda, 0x54, 0xbc, 0xd2, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x09, 0x81, 0x02, 0x62, 0xe6, 0x08, 0x00, 0x00,
}
