// Code generated by protoc-gen-go.
// source: task.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 获取玩家所有已经开始的任务，有进度的任务
type CTask struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7502" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CTask) Reset()                    { *m = CTask{} }
func (m *CTask) String() string            { return proto.CompactTextString(m) }
func (*CTask) ProtoMessage()               {}
func (*CTask) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

const Default_CTask_Code uint32 = 7502

func (m *CTask) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CTask_Code
}

type ProtoTask struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Kind             *uint32 `protobuf:"varint,2,req,name=kind" json:"kind,omitempty"`
	Count            *uint32 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	Rewards          *uint32 `protobuf:"varint,4,req,name=rewards" json:"rewards,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoTask) Reset()                    { *m = ProtoTask{} }
func (m *ProtoTask) String() string            { return proto.CompactTextString(m) }
func (*ProtoTask) ProtoMessage()               {}
func (*ProtoTask) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *ProtoTask) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTask) GetKind() uint32 {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return 0
}

func (m *ProtoTask) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ProtoTask) GetRewards() uint32 {
	if m != nil && m.Rewards != nil {
		return *m.Rewards
	}
	return 0
}

type STask struct {
	Code             *uint32      `protobuf:"varint,1,opt,name=code,def=7502" json:"code,omitempty"`
	Task             []*ProtoTask `protobuf:"bytes,2,rep,name=task" json:"task,omitempty"`
	Error            *uint32      `protobuf:"varint,3,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *STask) Reset()                    { *m = STask{} }
func (m *STask) String() string            { return proto.CompactTextString(m) }
func (*STask) ProtoMessage()               {}
func (*STask) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

const Default_STask_Code uint32 = 7502
const Default_STask_Error uint32 = 0

func (m *STask) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_STask_Code
}

func (m *STask) GetTask() []*ProtoTask {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *STask) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_STask_Error
}

type CGetTaskRewards struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=code,def=7503" json:"code,omitempty"`
	Id               *uint32 `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGetTaskRewards) Reset()                    { *m = CGetTaskRewards{} }
func (m *CGetTaskRewards) String() string            { return proto.CompactTextString(m) }
func (*CGetTaskRewards) ProtoMessage()               {}
func (*CGetTaskRewards) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

const Default_CGetTaskRewards_Code uint32 = 7503

func (m *CGetTaskRewards) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_CGetTaskRewards_Code
}

func (m *CGetTaskRewards) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type SGetTaskRewards struct {
	Code             *uint32    `protobuf:"varint,1,opt,name=code,def=7503" json:"code,omitempty"`
	Task             *ProtoTask `protobuf:"bytes,2,req,name=task" json:"task,omitempty"`
	Rewards          *uint32    `protobuf:"varint,3,req,name=rewards" json:"rewards,omitempty"`
	Error            *uint32    `protobuf:"varint,4,opt,name=error,def=0" json:"error,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *SGetTaskRewards) Reset()                    { *m = SGetTaskRewards{} }
func (m *SGetTaskRewards) String() string            { return proto.CompactTextString(m) }
func (*SGetTaskRewards) ProtoMessage()               {}
func (*SGetTaskRewards) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

const Default_SGetTaskRewards_Code uint32 = 7503
const Default_SGetTaskRewards_Error uint32 = 0

func (m *SGetTaskRewards) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SGetTaskRewards_Code
}

func (m *SGetTaskRewards) GetTask() *ProtoTask {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *SGetTaskRewards) GetRewards() uint32 {
	if m != nil && m.Rewards != nil {
		return *m.Rewards
	}
	return 0
}

func (m *SGetTaskRewards) GetError() uint32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Default_SGetTaskRewards_Error
}

// 任务更新
type SUpdateTask struct {
	Code             *uint32      `protobuf:"varint,1,opt,name=code,def=7505" json:"code,omitempty"`
	Task             []*ProtoTask `protobuf:"bytes,2,rep,name=task" json:"task,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SUpdateTask) Reset()                    { *m = SUpdateTask{} }
func (m *SUpdateTask) String() string            { return proto.CompactTextString(m) }
func (*SUpdateTask) ProtoMessage()               {}
func (*SUpdateTask) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{5} }

const Default_SUpdateTask_Code uint32 = 7505

func (m *SUpdateTask) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Default_SUpdateTask_Code
}

func (m *SUpdateTask) GetTask() []*ProtoTask {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*CTask)(nil), "protocol.CTask")
	proto.RegisterType((*ProtoTask)(nil), "protocol.ProtoTask")
	proto.RegisterType((*STask)(nil), "protocol.STask")
	proto.RegisterType((*CGetTaskRewards)(nil), "protocol.CGetTaskRewards")
	proto.RegisterType((*SGetTaskRewards)(nil), "protocol.SGetTaskRewards")
	proto.RegisterType((*SUpdateTask)(nil), "protocol.SUpdateTask")
}

var fileDescriptor12 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0x49, 0x9a, 0xa0, 0xbe, 0xb3, 0x54, 0xe2, 0x25, 0xe0, 0xa5, 0xe6, 0xd4, 0x53, 0x99,
	0x93, 0x21, 0x78, 0x9d, 0xe2, 0x75, 0x58, 0xfd, 0x01, 0xa1, 0xc9, 0x61, 0x44, 0x96, 0x91, 0x46,
	0xfc, 0xfb, 0x92, 0xcc, 0x59, 0x0f, 0x16, 0x7a, 0x0a, 0x5f, 0xf2, 0xbd, 0x79, 0x9f, 0x07, 0x88,
	0x7a, 0x70, 0xed, 0x21, 0xf8, 0xe8, 0xc5, 0x79, 0x3e, 0x7a, 0xff, 0xa1, 0x6e, 0xc0, 0x37, 0x6f,
	0x7a, 0x70, 0x42, 0x80, 0xf5, 0xde, 0x58, 0x49, 0x6a, 0xd2, 0x94, 0x8f, 0xec, 0x61, 0xbd, 0x5c,
	0xa9, 0x67, 0x5c, 0x6c, 0xd3, 0x62, 0x5e, 0x00, 0xe8, 0xce, 0x48, 0x52, 0xd3, 0xa6, 0x14, 0x97,
	0x60, 0x6e, 0xb7, 0x37, 0x92, 0xe6, 0xa9, 0x04, 0xef, 0xfd, 0xe7, 0x3e, 0xca, 0x22, 0x8f, 0x15,
	0xce, 0x82, 0xfd, 0xd2, 0xc1, 0x0c, 0x92, 0xa5, 0x0b, 0xb5, 0x05, 0xef, 0xa6, 0x3a, 0xc4, 0x2d,
	0x58, 0x02, 0x93, 0xb4, 0x2e, 0x9a, 0xc5, 0xea, 0xba, 0x3d, 0x91, 0xb5, 0x63, 0xf3, 0x15, 0xb8,
	0x0d, 0xc1, 0x07, 0x59, 0xe4, 0x1c, 0x59, 0xaa, 0x3b, 0x54, 0x9b, 0x17, 0x1b, 0xd3, 0xeb, 0xeb,
	0xb1, 0xea, 0x9f, 0xbf, 0xef, 0x7f, 0x90, 0x33, 0xa4, 0x72, 0xa8, 0xba, 0x19, 0x91, 0x11, 0x87,
	0x4e, 0xe1, 0xfc, 0xf1, 0x3b, 0x0a, 0xff, 0xf2, 0xb1, 0x13, 0xdf, 0x13, 0x16, 0xdd, 0xfb, 0xc1,
	0xe8, 0x68, 0x27, 0xbc, 0xd7, 0x33, 0xbc, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xcc, 0x70,
	0x01, 0xb2, 0x01, 0x00, 0x00,
}
